project: 
  type: website

website: 
  title: "My Website"
  sidebar: 
    contents: 
      - index.qmd
      - callout-boxes.qmd
      - about.qmd
  navbar: 
    left: 
      - index.qmd
      - callout-boxes.qmd

format: 
  html: 
    theme: 
      light: flatly
      dark: darkly
    toc: true
execute: 
  freeze: auto